#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]
cm = ["commit"]
init = ["git", "init", "--colocate"]
adv = ["bookmark", "set", "-r", "@-"]
push = ["git", "push", "--bookmark"]

[user]
name = "csepulveda-dev"
email = "dev@camilosep.com"
