#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]
cm = ["commit"]
init = ["git", "init", "--colocate"]
adv = ["bookmark", "set", "-r", "@-"]
push = ["git", "push", "--bookmark"]
fetch = ["git", "fetch"]
sq = ["squash"]

[user]
name = "csepulveda-gg"
email = "c.sepulveda@appleid.glossgenius.com"

[signing]
behavior = "own"
backend = "ssh"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
backends.ssh.allowed-signers = "/Users/csepulveda-gg/.ssh/allowed_signers"
